---
resources:
- name: code
  type: git
  source:
    uri: https://github.com/gayatrisingh31/node-hello
    branch: main
jobs:
  - name: node-hello
    plan:
    - get: code
      trigger: true
    - task: install
      config:
        platform: linux
        image-resource:
          type: docker-hub
          source: {repository: node}
        inputs:
         - name: code
        run:
           path: npm
        args:
            - npm install

